### ISSUE TITLE
The name of the tool appears with the word "cloud" in a new tab.

### ISSUE THREAD

**Issue by ZlatanPrasovic** [Kentico/kontent-template-manager#34]
### Brief bug description
Since the rebranding happened we should move away from using "cloud" and lean more towards "Kontent"

### Repro steps

1. Go to https://kentico.github.io/kontent-template-manager/
2. See the name in the tab "Kentico Cloud Manager"

### Expected behavior
The tab should show "Kentico Kontent Template Manager"

### Test environment

  - Browser chrome, mozzila

### Screenshots

![ex1chrome](https://user-images.githubusercontent.com/54852412/69549047-d454e300-0f98-11ea-8f67-2573f03228a5.png)
![ex2firefox](https://user-images.githubusercontent.com/54852412/69549065-dae35a80-0f98-11ea-9cfc-a3967e35aa66.png)

Add links to screenshots, if possible.

**Comment by Simply007** [comment]
I think that one was fixed as well @Enngage 💪

**Comment by Enngage** [comment]
Oh yeah, thanks @Simply007 :-)
