### ISSUE TITLE
Load template list from local build folder not from github

### ISSUE THREAD

**Issue by Simply007** [Kentico/kontent-template-manager#40]
### Motivation

It would be great to have Netlify preview in place for the pull requests.

Unfortunately, the template manager is loading JSON directly from the `master` branch from Github, so Netlify preview is not able to showcase the preview with the newly added items.

### Proposed solution

I would vote to use local file (include the JSON in the deployed build - not sure how - and then load it as a local source using HTTP client /templates/list.json).

### Additional context

https://github.com/Kentico/kontent-template-manager/pull/39

**Comment by Enngage** [comment]
Fixed by https://github.com/Kentico/kontent-template-manager/commit/a7279ea54a7da93f228ec3eec8c46326b91086c6

**Comment by Enngage** [comment]
Fixed by https://github.com/Kentico/kontent-template-manager/commit/a7279ea54a7da93f228ec3eec8c46326b91086c6

**Comment by Enngage** [comment]
Fixed by https://github.com/Kentico/kontent-template-manager/commit/a7279ea54a7da93f228ec3eec8c46326b91086c6
