### ISSUE TITLE
Download button is not working. some errors issue are there please check as soon its possible

### ISSUE THREAD

**Issue by Manthan326** [Kentico/kontent-template-manager#53]
Download button is not work of "kontent tamplete manager app".

 Repro steps

1. Go to 'kontent tamplete manager'
2. Click on 'download tamplete'
3. new tab will opened.
4. See error"NOT FOUND"

<img width="573" alt="Untitled" src="https://user-images.githubusercontent.com/73227731/98242743-ec97f500-1f92-11eb-994a-70852ea2f8a4.png">

**Comment by Enngage** [comment]
fixed
